name: dd

on:
    push:
        branches: feature/1781_test

jobs:
    storybook-pie-docs-build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: dddddddd
              run: |

                  cd ./docs
                  git init
                  git checkout -b master
                  git config user.name "GH Pages Bot"
                  git config user.email "hello@ghbot.com"
                  git add .
                  git commit -m "Deploy Storybook and pie-docs to Github Pages"
                  git push --force --quiet https://oss.fin.navercorp.com/common-fe/pie master:test-github-pages
