name: Push Gihub-Pages

on:
    push:
        branches: test
    pull_request:
        branches: 
         - 'master'

jobs:
    storybook-pie-docs-build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: test push github-pages
              run: |
                  cd ./docs
                  git init
                  git checkout -b main
                  git config user.name "GH Pages Bot"
                  git config user.email "hello@ghbot.com"
                  git add .
                  git commit -m "Deploy Storybook and pie-docs to Github Pages"
                  git push --force --quiet https://github.com/hipppoSHL/movie_app main:test-github-pages
